skip_frontmatter: false

linters:
  CommentControlStatement:
    enabled: true

  ConsecutiveControlStatements:
    enabled: true
    max_consecutive: 2

  EmptyControlStatment:
    enabled: true

  ExplicitDiv:
    enabled: true

  LineLength:
    enabled: true
    max: 120

  RuboCop:
    enabled: true
    ignored_cops:
      - Lint/BlockAlignment
      - Lint/EndAlignment
      - Lint/Void
      - Metrics/LineLength
      - Style/AlignHash
      - Layout/AlignParameters
      - Style/BlockNesting
      - Style/FileName
      - Style/FirstParameterIndentation
      - Style/IfUnlessModifier
      - Style/IndentationConsistency
      - Layout/IndentationWidth
      - Style/Next
      - Layout/TrailingBlankLines
      - Style/TrailingWhitespace
      - Style/WhileUntilModifier
      - Style/NestedTernaryOperator

  TagCase:
    enabled: true

  TrailingWhitespace:
    enabled: true
